version: '3.4'

services:
  school_finder_api:
    container_name: school_finder_api
    hostname: school_finder_api
    build: .
    env_file:
      - .env
    networks: [default]
    ports:
      - 5001:80 
    environment:      
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - SchoolFinderSettings:ConnectionStrings:SchoolFinderDB=${SCHOOL_FINDER_CONNECTION}
    depends_on:
      school_finder_db:
        condition: service_healthy
        
  school_finder_db:
    container_name: school_finder_db
    hostname: school_finder_db
    image: postgres:15.4-alpine
    environment:
      POSTGRES_USER: ${DB_ROOT_USERNAME}
      POSTGRES_PASSWORD: ${DB_ROOT_PASSWORD}
    command: postgres -c 'max_connections=200' && postgres -c 'shared_buffers=24MB' 
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
      - ./.docker/db/create-databases.sql:/docker-entrypoint-initdb.d/create-databases.sql
    networks: [default]
    ports:
      - 5432:5432    
    healthcheck:
      test: "exit 0"
  
networks:
  default:    
    name: school_finder_network
